### ISSUE TITLE
writeDeclartion doesn't handle methods

### ISSUE THREAD

**Issue by RMcNeely** [RyanCavanaugh/dts-dom#20]
I'm not very familiar with TypeScript so forgive me if this is silly issue or in some way incompatible.

I would like to use this library to convert JSDoc comments to a typescript definition file (like the [tsd-jsdoc ](https://github.com/englercj/tsd-jsdoc) projcect) but I run into problems when comments hit the `writeDeclaration` function. In our library most everything is interpreted as a method by JSDocs since they exist inside our global namespace. There shouldn't theoretically be any reason they cannot be passed as an case in which calls `writeFunction`.

I've attempted to get this working to put in a PR but am running into some type errors that I'm working through, you might know a better way to resolve this.

**Comment by RyanCavanaugh** [comment]
A code sample of what you're trying to do and what error you're seeing would be very helpful

**Comment by RMcNeely** [comment]
Terminal on the left hand side and the compile index.js on the right
See below: 
![tsdoc error](https://cloud.githubusercontent.com/assets/2806302/25496630/9c771906-2b4f-11e7-9525-05c686a56b27.png)

The comment in question here is about a method on a web component. It's functionally fine if we treat it as a function. If you take a look at the commented out line in index.js you'll see what I've monkey patched in as a fix.

**Comment by RyanCavanaugh** [comment]
A method is *not* a declaration; it's a class member. It's illegal to try to write a method declaration at top-level or in a namespace. You should be adding function declarations to the namespace, not methods.
