### ISSUE TITLE
Class member function vs method

### ISSUE THREAD

**Issue by wehrstedt** [RyanCavanaugh/dts-dom#30]
Is there a specific reason why you differ between functionDeclaration and methodDeclaration?
I ask because I was wondering why my class members won't be parsed :D

**Comment by RyanCavanaugh** [comment]
They're different -- functions can have `export` but not `private` or `protected`; vice versa for methods. Methods can have quoted names, but function declarations can't.

**Comment by wehrstedt** [comment]
ah okay, that makes sense. Thanks
