### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by KingHenne** [RyanCavanaugh/dts-dom#35]
Following up on this [comment](https://github.com/RyanCavanaugh/dts-dom/pull/32#issuecomment-349125137):

> What happens if we add hundreds of tests like this, then decide that the default output formatting should place the brace on the next line, or that large type aliases of unions should be split into multiple lines? Now we have to hand-edit hundreds of string literals in a .ts file; that's a nightmare.

We could easily add snapshot tests with Jest to avoid migration issues like this. Would you be open to a PR that adds this?

**Comment by RyanCavanaugh** [comment]
Sure!
