### ISSUE TITLE
How to return a typed Promise from a method

### ISSUE THREAD

**Issue by mattinsler** [RyanCavanaugh/dts-dom#45]
I'm trying to generate the following:

```
declare interface PartitionService {
    shell(req: ShellRequest): Promise<ShellResponse>;
}
```

Everything works fine except for the `Promise<ShellResponse>`. I'm not sure how to generate that piece. Any help? Thanks!

**Comment by RyanCavanaugh** [comment]
Oddly enough, there currently isn't a way to reference a generic type. PRs welcomed

**Comment by RyanCavanaugh** [comment]
You can technically just lie and call `create.namedTypeReference("Promise<ShellResponse>")` though

**Comment by mattinsler** [comment]
Ha, I guess that'll work for now. =-)
