### ISSUE TITLE
Parameters with default value

### ISSUE THREAD

**Issue by wehrstedt** [RyanCavanaugh/dts-dom#46]
As far as I can see there is no possibility to create parameters with initial value like
```ts
function myFunc(param: boolean = false)
```

Do you have a suggestion how to extend the function [create.parameter](https://github.com/RyanCavanaugh/dts-dom/blob/master/lib/index.ts#L360) to pass in a default value? If a default value is passed, the parameter `flags` can be implicit set to `DeclarationFlags.Optional`.

I would create a PR, but I didn't find a good way to apply these changes without breaking the API. 
 Do you have any suggestions?

**Comment by RyanCavanaugh** [comment]
`dts-dom` is only for definition file syntax, and default values can't be specified in a .d.ts file
