### ISSUE TITLE
Thank you for including /lib in your npm packages!

### ISSUE THREAD

**Issue by junosuarez** [RyanCavanaugh/dts-dom#53]
Just came to say thank you. I'm writing some code that depends on the typescript types, based on the path inside the package (e.g. `require('dts-dom/lib/index.ts')`). I'm not asking for any changes, however- if in the future you decide to only include your built `/bin` directory (which many packages do), please consider it a breaking change for your version number. 🙏🏼

Thanks again for this useful package!

**Comment by RyanCavanaugh** [comment]
👍
