### ISSUE TITLE
Type alias NamespaceMember should include EnumDeclaration 

### ISSUE THREAD

**Issue by junoatscroll** [RyanCavanaugh/dts-dom#61]
This is the closest authoratative reference I could find, although it appears to be quite old: https://github.com/microsoft/TypeScript/blob/master/doc/spec.md#102-namespace-body

The following is valid typescript, according to my tsc@3.7.4:
```typescript
declare namespace N {
    enum E {
        A = "a",
        B = "b",
    }
}
```

and can be generated with
```typescript
const n = dom.create.namespace('N')
const e = dom.create.enum('E')
e.members.push(dom.create.enumValue('A','a'))
e.members.push(dom.create.enumValue('B','b'))
n.members.push(e)
dom.emit(n)
```

However the type of `n.members`, `NamespaceMember[]`, does not include `EnumDeclaration`.

In my code, I've worked around it with a `// @ts-ignore`

I'm happy to create a PR if you agree with this change.

**Comment by RyanCavanaugh** [comment]
I agree

**Comment by RyanCavanaugh** [comment]
Duplicate #51

**Comment by junoatscroll** [comment]
Ah, thanks for tagging as duplicate!
