### ISSUE TITLE
SPACE missing in function writeInterface() before keyword extends

### ISSUE THREAD

**Issue by kozi** [RyanCavanaugh/dts-dom#88]
`SPACE` missing in function `writeInterface()` before keyword `extends`.

<https://github.com/RyanCavanaugh/dts-dom/blob/8c14dd879d1da910d264e095bddfd61e2ce259cb/lib/index.ts#L1000>

<https://github.com/RyanCavanaugh/dts-dom/commit/a089078c26351f8810b50a25d487ee58b257c1bb#diff-d5a4b3a0309f2337144861084c1014523cced561eb722cb9684c63f5e41e0567L972-R1004>

**Comment by AmitFeldman** [comment]
This is also affecting our project. @RyanCavanaugh Why not merge this fix?
